version: '3'

services:
  backend:
    build: https://github.com/Project-Reclass/toynet-flask.git#e0a3d0295497f2e5a347c374a6d44ce431f940f3
    networks:
      - reclass_network
    ports:
      - "5000:5000"

  proxy:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    networks:
      - reclass_network
    environment:
      - SERVER_URI="http://backend:5000"
    ports:
      - "8080:80"

networks:
  reclass_network:
