version: '3'

services:
  backend:
    build: https://github.com/Project-Reclass/toynet-django.git#PRODUCTION
    networks:
      - reclass_network
    environment:
      - SECRET_KEY="iamnotaverysecretkey"
    ports:
      - "8000:8000"

  proxy:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    networks:
      - reclass_network
    environment:
      - SERVER_URI="http://backend:8000"
    ports:
      - "8080:80"

networks:
  reclass_network: