version: '3'

services:
  miniflask:
    image: projectreclass/toynet-mininet:1174f9d091ed036f7b958e7e84c0bface8bf32cb

  backend:
    depends_on:
      - miniflask
    image: projectreclass/toynet-backend:1174f9d091ed036f7b958e7e84c0bface8bf32cb
    privileged: true
    ports:
      - "5000:5000"
    environment:
      - COMPOSE_NETWORK=toynet_mininet
      - TOYNET_IMAGE_TAG=projectreclass/toynet-mininet:1174f9d091ed036f7b958e7e84c0bface8bf32cb
      - FLASK_APP=flasksrc
      - MINI_FLASK_PORT=5000

    networks:
      - reclass_network
      - toynet_mininet
    volumes:
      - /lib/modules:/lib/modules
      - /var/run/docker.sock:/var/run/docker.sock

  proxy:
    depends_on:
      - backend
    build:
      context: ./
      dockerfile: dev.Dockerfile
    networks:
      - reclass_network
    environment:
      - SERVER_URI="http://backend:5000"
    ports:
      - "8080:80"

networks:
  reclass_network:
  toynet_mininet:
    name: toynet_mininet
