name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: cd $GITHUB_WORKSPACE; npm install
    - name: Run tests
      run: npm test

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm i
      - run: npm run style:check

  check-types:
    name: check types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm i
      - run: npm run check-types
    
  check-build:
    name: check build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm i
      - run: npm run build
